const translations = {
  es: {
    "nav.menu": "Carta",
    "nav.orders": "Encargos",
    "nav.visit": "Visitanos",
    "hero.place": "Luanco, Asturias",
    "hero.lead": "Cafe, bolleria de mantequilla, tostadas y dulces caseros preparados cada manana en nuestro propio obrador.",
    "hero.menuButton": "Ver carta",
    "note.kicker": "100% casero",
    "note.title": "Hecho cada manana",
    "note.copy": "Tarta de queso, tortilla de patata, empanada y fuera de carta por encargo.",
    "menu.kicker": "Carta",
    "menu.title": "Cafe, dulce y salado",
    "section.coffee": "Cafe",
    "section.tea": "Te",
    "section.others": "Otros",
    "section.sweet": "Dulce",
    "section.pastry": "Bolleria",
    "section.savory": "Salado",
    "section.toasts": "Tostadas <small>Desayunos</small>",
    "section.bikinis": "Bikinis",
    "section.beers": "Cervezas",
    "section.wines": "Vinos",
    "section.softDrinks": "Refrescos",
    "sweet.note": "100% casero, hecho en nuestro propio obrador cada manana.",
    "pastry.note": "100% mantequilla",
    "item.cafeSolo": "Cafe solo",
    "item.cafeCortado": "Cafe cortado",
    "item.decaf": "Descafeinado de sobre",
    "item.cafeLeche": "Cafe con leche",
    "item.cafeVaso": "Cafe con leche en vaso",
    "item.capuchino": "Capuchino",
    "item.moka": "Moka",
    "item.cafeBaylies": "Cafe con leche, hielo y Baileys",
    "item.infusion": "Infusion",
    "item.teAmericano": "Te americano",
    "item.teHelado": "Te helado <em>Lima - Mango - Frambuesa</em>",
    "item.matcha": "Te Matcha",
    "item.hotChocolate": "Chocolate caliente",
    "item.orangeJuice": "Zumo natural de naranja",
    "item.extraShot": "Doble carga",
    "item.plantMilk": "Leche vegetal",
    "item.cookies": "Cookies <em>Chocolate - Tres chocolates</em>",
    "item.lemonCake": "Bizcocho de limon",
    "item.mantecado": "Mantecado",
    "item.muffins": "Muffins <em>Chocolate - Frutos rojos</em>",
    "item.palmerita": "Palmerita de chocolate",
    "item.almondRoll": "Roll Almendra",
    "item.yorkcheese": "Yorkcheese <em>Masa de croissant con jamon y queso</em>",
    "item.pincho": "Pincho <em>con mayonesa: lomo, pollo empanado o bacon</em>",
    "item.tortillaPincho": "Pincho de tortilla",
    "item.butterJam": "Mantequilla y mermelada",
    "item.tomatoOil": "Tomate y aceite",
    "item.tomatoAvocado": "Tomate y aguacate",
    "item.tomatoHam": "Tomate y paletilla",
    "item.tomatoAvocadoHam": "Tomate, aguacate y paletilla",
    "item.mixto": "Mixto",
    "item.trufado": "Trufado",
    "drinks.kicker": "Bebidas y tienda",
    "drinks.title": "Cervezas, vinos y refrescos",
    "item.glutenFreeMahou": "Mahou sin gluten",
    "item.alhambra": "Alhambra <em>Verde - Roja</em>",
    "item.tintoVerano": "Tinto de verano",
    "item.water": "Agua",
    "item.sparklingWater": "Agua con gas",
    "item.peachJuice": "Zumo pina / melocoton",
    "item.fanta": "Fanta de naranja",
    "item.fuzePassion": "Fuze Tea Maracuya",
    "item.blend": "250 gr de nuestro blend <em>En grano o molido</em>",
    "item.glutenProducts": "Productos 100% sin gluten <em>Preguntar en el local</em>",
    "orders.kicker": "Encargos",
    "orders.title": "Tambien hacemos encargos",
    "orders.cheesecake": "Tarta de queso",
    "orders.tortilla": "Tortilla de patata",
    "orders.copy": "Pregunta por nuestros fuera de carta: eclair, tortitas y lemon pie.",
    "visit.kicker": "Visitanos",
    "visit.map": "Abrir mapa"
  },
  en: {
    "nav.menu": "Menu",
    "nav.orders": "Orders",
    "nav.visit": "Visit",
    "hero.place": "Luanco, Asturias",
    "hero.lead": "Coffee, butter pastries, toast and homemade sweets prepared every morning in our own bakery.",
    "hero.menuButton": "View menu",
    "note.kicker": "100% homemade",
    "note.title": "Made every morning",
    "note.copy": "Cheesecake, Spanish omelette, empanada and off-menu items available to order.",
    "menu.kicker": "Menu",
    "menu.title": "Coffee, sweet and savory",
    "section.coffee": "Coffee",
    "section.tea": "Tea",
    "section.others": "Other drinks",
    "section.sweet": "Sweet",
    "section.pastry": "Pastry",
    "section.savory": "Savory",
    "section.toasts": "Toasts <small>Breakfast</small>",
    "section.bikinis": "Bikinis",
    "section.beers": "Beers",
    "section.wines": "Wines",
    "section.softDrinks": "Soft drinks",
    "sweet.note": "100% homemade, made every morning in our own bakery.",
    "pastry.note": "100% butter",
    "item.cafeSolo": "Black coffee",
    "item.cafeCortado": "Cortado",
    "item.decaf": "Decaf sachet",
    "item.cafeLeche": "Coffee with milk",
    "item.cafeVaso": "Coffee with milk in a glass",
    "item.capuchino": "Cappuccino",
    "item.moka": "Mocha",
    "item.cafeBaylies": "Coffee with milk, ice and Baileys",
    "item.infusion": "Herbal infusion",
    "item.teAmericano": "American tea",
    "item.teHelado": "Iced tea <em>Lime - Mango - Raspberry</em>",
    "item.matcha": "Matcha tea",
    "item.hotChocolate": "Hot chocolate",
    "item.orangeJuice": "Fresh orange juice",
    "item.extraShot": "Extra shot",
    "item.plantMilk": "Plant-based milk",
    "item.cookies": "Cookies <em>Chocolate - Triple chocolate</em>",
    "item.lemonCake": "Lemon cake",
    "item.mantecado": "Shortbread cake",
    "item.muffins": "Muffins <em>Chocolate - Red berries</em>",
    "item.palmerita": "Chocolate palmier",
    "item.almondRoll": "Almond roll",
    "item.yorkcheese": "Yorkcheese <em>Croissant dough with ham and cheese</em>",
    "item.pincho": "Pincho <em>with mayonnaise: pork loin, breaded chicken or bacon</em>",
    "item.tortillaPincho": "Spanish omelette pincho",
    "item.butterJam": "Butter and jam",
    "item.tomatoOil": "Tomato and olive oil",
    "item.tomatoAvocado": "Tomato and avocado",
    "item.tomatoHam": "Tomato and cured ham",
    "item.tomatoAvocadoHam": "Tomato, avocado and cured ham",
    "item.mixto": "Ham and cheese",
    "item.trufado": "Truffled",
    "drinks.kicker": "Drinks and store",
    "drinks.title": "Beers, wines and soft drinks",
    "item.glutenFreeMahou": "Gluten-free Mahou",
    "item.alhambra": "Alhambra <em>Green - Red</em>",
    "item.tintoVerano": "Tinto de verano",
    "item.water": "Water",
    "item.sparklingWater": "Sparkling water",
    "item.peachJuice": "Pineapple / peach juice",
    "item.fanta": "Orange Fanta",
    "item.fuzePassion": "Fuze Tea Passion Fruit",
    "item.blend": "250 g of our blend <em>Whole bean or ground</em>",
    "item.glutenProducts": "100% gluten-free products <em>Ask in store</em>",
    "orders.kicker": "Orders",
    "orders.title": "We also take orders",
    "orders.cheesecake": "Cheesecake",
    "orders.tortilla": "Spanish omelette",
    "orders.copy": "Ask about our off-menu items: eclair, pancakes and lemon pie.",
    "visit.kicker": "Visit us",
    "visit.map": "Open map"
  }
};

const buttons = document.querySelectorAll("[data-lang]");
const translatable = document.querySelectorAll("[data-i18n]");
const storedLanguage = localStorage.getItem("corner-language");
const initialLanguage = storedLanguage || "es";

function setLanguage(language) {
  const dictionary = translations[language] || translations.es;
  document.documentElement.lang = language;
  translatable.forEach((node) => {
    const key = node.dataset.i18n;
    if (dictionary[key]) node.innerHTML = dictionary[key];
  });
  buttons.forEach((button) => {
    const isActive = button.dataset.lang === language;
    button.setAttribute("aria-pressed", String(isActive));
  });
  localStorage.setItem("corner-language", language);
}

buttons.forEach((button) => {
  button.addEventListener("click", () => setLanguage(button.dataset.lang));
});

setLanguage(initialLanguage);
