const translations = {
  es: {
    "nav.menu": "Carta",
    "nav.orders": "Encargos",
    "nav.visit": "Visítanos",
    "hero.place": "Luanco, Asturias",
    "hero.lead": "Café, bollería de mantequilla, tostadas y dulces caseros preparados cada mañana en nuestro propio obrador.",
    "hero.menuButton": "Ver carta",
    "photo.kicker": "Dentro de The Corner",
    "photo.title": "De la bandeja<br>a la mesa.",
    "photo.intro": "Hojaldre, café y un rincón donde quedarse un poco más.",
    "note.kicker": "100% casero",
    "note.title": "Hecho cada mañana",
    "note.copy": "Tarta de queso, tortilla de patata, empanada y fuera de carta por encargo.",
    "origin.kicker": "Nuestro café",
    "origin.title": "Dos fincas.<br>Un solo ensamble.",
    "origin.intro": "<em>The Corner</em> presenta un ensamble de dos cafés diferenciados del programa Café Circular®️ en la región de la Sierra Madre Oriental en México. Este ensamble proviene de dos fincas: <em>Finca El Chorrito</em>, ubicada a 900 msnm en una fauna selvática, y <em>Finca La Capilla</em>, situada a 1100 msnm en una foresta mesófila.",
    "origin.flavour": "El café de <em>Finca El Chorrito</em> es semi lavado, ofreciendo un cuerpo denso y un resabio a avellana. Por otro lado, el café de <em>Finca La Capilla</em> aporta una acidez cítrica balanceada y un gusto achocolatado. La mezcla es 60% variedad Gesha y 40% híbridos de Timor.",
    "origin.roast": "Este ensamble es ideal para espresso, siendo cremoso, corposo y aromático, y también perfecto para cappuccino o latte. El tostado, realizado por el maestro tostador de Cafés El Globo, es omniroast, versátil tanto para espressos como para filtros.",
    "origin.welcome": "Bienvenido a la cultura del café y disfruta del mejor sabor.",
    "origin.farm": "Finca El Chorrito",
    "origin.farmTwo": "Finca La Capilla",
    "origin.elevationUnit": "msnm",
    "origin.blend": "Variedad",
    "origin.roastLabel": "Tostado",
    "origin.omniroast": "Omniroast",
    "menu.kicker": "Carta",
    "menu.title": "Café, dulce y salado",
    "section.coffee": "Café",
    "section.tea": "Té",
    "section.others": "Otros",
    "section.sweet": "Dulce",
    "section.pastry": "Bollería",
    "section.savory": "Salado",
    "section.toasts": "Tostadas <small>Desayunos</small>",
    "section.bikinis": "Bikinis",
    "section.beers": "Cervezas",
    "section.wines": "Vinos",
    "section.softDrinks": "Refrescos",
    "sweet.note": "100% casero, hecho en nuestro propio obrador cada mañana.",
    "pastry.note": "100% mantequilla",
    "item.cafeSolo": "Café solo",
    "item.cafeCortado": "Café cortado",
    "item.decaf": "Descafeinado de sobre",
    "item.cafeLeche": "Café con leche",
    "item.cafeVaso": "Café con leche en vaso",
    "item.capuchino": "Capuchino",
    "item.moka": "Moka",
    "item.cafeBaylies": "Café con leche, hielo y Baileys",
    "item.infusion": "Infusión",
    "item.teAmericano": "Té americano",
    "item.teHelado": "Té helado <em>Lima - Mango - Frambuesa</em>",
    "item.matcha": "Té matcha",
    "item.hotChocolate": "Chocolate caliente",
    "item.orangeJuice": "Zumo natural de naranja",
    "item.extraShot": "Doble carga",
    "item.plantMilk": "Leche vegetal",
    "item.cookies": "Cookies <em>Chocolate - Tres chocolates</em>",
    "item.lemonCake": "Bizcocho de limón",
    "item.mantecado": "Mantecado",
    "item.muffins": "Muffins <em>Chocolate - Frutos rojos</em>",
    "item.palmerita": "Palmerita de chocolate",
    "item.almondRoll": "Roll Almendra",
    "item.yorkcheese": "Yorkcheese <em>Masa de croissant con jamón y queso</em>",
    "item.pincho": "Pincho <em>con mayonesa: lomo, pollo empanado o bacon</em>",
    "item.tortillaPincho": "Pincho de tortilla",
    "item.butterJam": "Mantequilla y mermelada",
    "item.tomatoOil": "Tomate y aceite",
    "item.tomatoAvocado": "Tomate y aguacate",
    "item.tomatoHam": "Tomate y paletilla",
    "item.tomatoAvocadoHam": "Tomate, aguacate y paletilla",
    "item.mixto": "Mixto",
    "item.trufado": "Trufado",
    "drinks.kicker": "Bebidas y tienda",
    "drinks.title": "Cervezas, vinos y refrescos",
    "item.glutenFreeMahou": "Mahou sin gluten",
    "item.alhambra": "Alhambra <em>Verde - Roja</em>",
    "item.tintoVerano": "Tinto de verano",
    "item.water": "Agua",
    "item.sparklingWater": "Agua con gas",
    "item.peachJuice": "Zumo piña / melocotón",
    "item.fanta": "Fanta de naranja",
    "item.fuzePassion": "Fuze Tea Maracuyá",
    "item.blend": "250 gr de nuestro blend <em>En grano o molido</em>",
    "item.glutenProducts": "Productos 100% sin gluten <em>Preguntar en el local</em>",
    "orders.kicker": "Encargos",
    "orders.title": "También hacemos encargos",
    "orders.cheesecake": "Tarta de queso",
    "orders.tortilla": "Tortilla de patata",
    "orders.copy": "Pregunta por nuestros fuera de carta: éclair, tortitas y lemon pie.",
    "visit.kicker": "Visítanos",
    "visit.map": "Abrir mapa"
  },
  en: {
    "nav.menu": "Menu",
    "nav.orders": "Orders",
    "nav.visit": "Visit",
    "hero.place": "Luanco, Asturias",
    "hero.lead": "Coffee, butter pastries, toast and homemade sweets prepared every morning in our own bakery.",
    "hero.menuButton": "View menu",
    "photo.kicker": "Inside The Corner",
    "photo.title": "From the tray<br>to the table.",
    "photo.intro": "Flaky pastry, coffee, and a corner worth lingering in.",
    "note.kicker": "100% homemade",
    "note.title": "Made every morning",
    "note.copy": "Cheesecake, Spanish omelette, empanada and off-menu items available to order.",
    "origin.kicker": "Our coffee",
    "origin.title": "Two farms.<br>One blend.",
    "origin.intro": "<em>The Corner</em> presents a blend of two differentiated coffees from the Café Circular®️ program in the Sierra Madre Oriental region of Mexico. This blend comes from two farms: <em>Finca El Chorrito</em>, located at 900 meters above sea level in a jungle fauna, and <em>Finca La Capilla</em>, situated at 1100 meters above sea level in a mesophilic forest.",
    "origin.flavour": "The coffee from <em>Finca El Chorrito</em> is semi-washed, offering a dense body and a hazelnut aftertaste. Meanwhile, the coffee from <em>Finca La Capilla</em> provides a balanced citrus acidity and a chocolaty taste. The blend is 60% Gesha variety and 40% Timor hybrids.",
    "origin.roast": "This blend is ideal for espresso, being creamy, full-bodied, and aromatic, and also perfect for cappuccino or latte. The roasting, done by the master roaster at Cafés El Globo, is omniroast, versatile for both espressos and filters.",
    "origin.welcome": "Welcome to the coffee culture and enjoy the best taste.",
    "origin.farm": "Finca El Chorrito",
    "origin.farmTwo": "Finca La Capilla",
    "origin.elevationUnit": "m a.s.l.",
    "origin.blend": "Variety",
    "origin.roastLabel": "Roast",
    "origin.omniroast": "Omniroast",
    "menu.kicker": "Menu",
    "menu.title": "Coffee, sweet and savory",
    "section.coffee": "Coffee",
    "section.tea": "Tea",
    "section.others": "Other drinks",
    "section.sweet": "Sweet",
    "section.pastry": "Pastry",
    "section.savory": "Savory",
    "section.toasts": "Toasts <small>Breakfast</small>",
    "section.bikinis": "Bikinis",
    "section.beers": "Beers",
    "section.wines": "Wines",
    "section.softDrinks": "Soft drinks",
    "sweet.note": "100% homemade, made every morning in our own bakery.",
    "pastry.note": "100% butter",
    "item.cafeSolo": "Black coffee",
    "item.cafeCortado": "Cortado",
    "item.decaf": "Decaf sachet",
    "item.cafeLeche": "Coffee with milk",
    "item.cafeVaso": "Coffee with milk in a glass",
    "item.capuchino": "Cappuccino",
    "item.moka": "Mocha",
    "item.cafeBaylies": "Coffee with milk, ice and Baileys",
    "item.infusion": "Herbal infusion",
    "item.teAmericano": "American tea",
    "item.teHelado": "Iced tea <em>Lime - Mango - Raspberry</em>",
    "item.matcha": "Matcha tea",
    "item.hotChocolate": "Hot chocolate",
    "item.orangeJuice": "Fresh orange juice",
    "item.extraShot": "Extra shot",
    "item.plantMilk": "Plant-based milk",
    "item.cookies": "Cookies <em>Chocolate - Triple chocolate</em>",
    "item.lemonCake": "Lemon cake",
    "item.mantecado": "Shortbread cake",
    "item.muffins": "Muffins <em>Chocolate - Red berries</em>",
    "item.palmerita": "Chocolate palmier",
    "item.almondRoll": "Almond roll",
    "item.yorkcheese": "Yorkcheese <em>Croissant dough with ham and cheese</em>",
    "item.pincho": "Pincho <em>with mayonnaise: pork loin, breaded chicken or bacon</em>",
    "item.tortillaPincho": "Spanish omelette pincho",
    "item.butterJam": "Butter and jam",
    "item.tomatoOil": "Tomato and olive oil",
    "item.tomatoAvocado": "Tomato and avocado",
    "item.tomatoHam": "Tomato and cured ham",
    "item.tomatoAvocadoHam": "Tomato, avocado and cured ham",
    "item.mixto": "Ham and cheese",
    "item.trufado": "Truffled",
    "drinks.kicker": "Drinks and store",
    "drinks.title": "Beers, wines and soft drinks",
    "item.glutenFreeMahou": "Gluten-free Mahou",
    "item.alhambra": "Alhambra <em>Green - Red</em>",
    "item.tintoVerano": "Tinto de verano",
    "item.water": "Water",
    "item.sparklingWater": "Sparkling water",
    "item.peachJuice": "Pineapple / peach juice",
    "item.fanta": "Orange Fanta",
    "item.fuzePassion": "Fuze Tea Passion Fruit",
    "item.blend": "250 g of our blend <em>Whole bean or ground</em>",
    "item.glutenProducts": "100% gluten-free products <em>Ask in store</em>",
    "orders.kicker": "Orders",
    "orders.title": "We also take orders",
    "orders.cheesecake": "Cheesecake",
    "orders.tortilla": "Spanish omelette",
    "orders.copy": "Ask about our off-menu items: eclair, pancakes and lemon pie.",
    "visit.kicker": "Visit us",
    "visit.map": "Open map"
  }
};

const buttons = document.querySelectorAll("[data-lang]");
const translatable = document.querySelectorAll("[data-i18n]");
const storedLanguage = localStorage.getItem("corner-language");
const initialLanguage = storedLanguage || "es";

function setLanguage(language) {
  const dictionary = translations[language] || translations.es;
  document.documentElement.lang = language;
  translatable.forEach((node) => {
    const key = node.dataset.i18n;
    if (dictionary[key]) node.innerHTML = dictionary[key];
  });
  buttons.forEach((button) => {
    const isActive = button.dataset.lang === language;
    button.setAttribute("aria-pressed", String(isActive));
  });
  localStorage.setItem("corner-language", language);
}

buttons.forEach((button) => {
  button.addEventListener("click", () => setLanguage(button.dataset.lang));
});

setLanguage(initialLanguage);
